"""Phases 8+11 scoring API: feature store, audit log, governance, stress-test, streaming.

Endpoints (all under /api — every pre-Phase-8 endpoint keeps its shape; the
React dashboard depends on them):
  GET  /api/loans                 — sample of scoreable loans across the grade spectrum
  POST /api/score/{loan_id}       — full §11.3 six-part output; features from the ONLINE store
  GET  /api/explain/{loan_id}     — cached explanation, no re-scoring (§17)
  GET  /api/metrics               — consolidated model-comparison tables
  POST /api/override/{loan_id}    — accept | modify | override (reason mandatory for both
                                    modify and override; modify records a delta) (§12.5)
  GET  /api/overrides             — recent decisions from the append-only log
  GET  /api/portfolio/summary     — grade distribution + expected-loss rate (§17)
  POST /api/stress-test           — §12.7 scenario simulator (pure re-inference)
  GET  /api/fairness/audit        — §12.6 disparate-impact summary
  GET  /api/rbi/mapping           — §12.4 ML-trigger -> RBI indicator mapping
  GET  /api/drift/report          — latest Phase 10 drift summary (or not_yet_generated)
  GET  /api/alerts                — streaming re-score alerts (grade moved) (§14)
  GET  /api/timeline/{loan_id}    — silent risk-trajectory timeline (§14)
  POST /api/events/simulate       — publish a GST/bank/repayment event onto the bus (§14)

Expected-loss convention (stated in every EL payload): the serving snapshot
carries NO monetary exposure amounts, so EL = PD x LGD x EAD (plan.md §12.7)
is reported as a portfolio expected-loss RATE per unit EAD with LGD = 0.45,
the Basel foundation-IRB senior-unsecured default.

Local-environment constraints (honest): no Docker daemon, so SQLite backs the
online feature store and audit log (DATABASE_URL names the docker-compose
'postgres' upgrade path) and the event bus is in-process (KAFKA_BOOTSTRAP_SERVERS
switches to Redpanda/Kafka via kafka-python).

Run:  uvicorn src.serving.app:app --port 8000
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

import joblib
import numpy as np
import pandas as pd
from fastapi import APIRouter, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from src.explainability.counterfactual import find_counterfactual
from src.explainability.narrative import generate_narrative
from src.explainability.uncertainty import confidence_band
from src.governance.fairness import fairness_audit
from src.governance.rbi_mapping import get_rbi_mapping
from src.models.calibration import (
    ACTION_BY_GRADE,
    GLOBAL_KEY,
    GRADE_BANDS,
    apply_calibration,
    pd_to_grade,
)
from src.models.explain import build_explainer, top_drivers
from src.models.hazard import MAX_MONTHS, align_columns, build_model_matrix, cumulative_pd
from src.models.router import route_segment
from src.models.thin_file import THIN_FILE_FEATURES, tabpfn_top_drivers
from src.serving import feature_store, store
from src.streaming.bus import get_bus
from src.streaming.consumer import EVENT_TYPES, EVENTS_TOPIC, make_feature_refresh_handler

DISCLOSURE = (
    "AI-assisted assessment. This risk score was generated by a machine-learning "
    "model and translated from verified model attributions. A human officer holds "
    "final decision authority and may override it."
)

# EL = PD x LGD x EAD (plan.md §12.7). No monetary amounts in the serving
# snapshot -> expected loss is a RATE per unit EAD; LGD 0.45 = Basel
# foundation-IRB senior-unsecured default.
LGD = 0.45
EL_CONVENTION = {
    "formula": "EL = PD x LGD x EAD (plan.md §12.7)",
    "lgd": LGD,
    "lgd_basis": "Basel foundation-IRB senior-unsecured default (45%)",
    "ead": "unit (per 1 currency unit of exposure)",
    "note": (
        "The serving snapshot carries no monetary exposure amounts, so expected "
        "loss is reported as a portfolio expected-loss RATE per unit EAD."
    ),
}

GRADES = [g for _, g in GRADE_BANDS]
STRESS_SHOCKS = ("revenue", "rate", "sector_demand")
STRESS_MAX_LOANS = 5000  # 12-month expansion => 60k person-period rows, sub-second on LightGBM
THIN_FILE_BACKGROUND_ROWS = 128  # SHAP background pool for the TabPFN explainer

# Columns that must stay strings when a feature JSON payload is rebuilt into a frame.
STRING_COLS = {
    "loan_type_segment",
    "sector_segment",
    "data_richness",
    "graph_data_provenance",
    "sentiment_label",
    "text_data_provenance",
}

app = FastAPI(title="MSME RiskPulse — Scoring API")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)

api = APIRouter(prefix="/api")

STATE: dict = {}


@app.on_event("startup")
def load_artifacts():
    # joblib.load here only touches models/*.joblib artifacts produced by this
    # repo's own phase scripts (trusted, project-internal) — same pattern as
    # scripts/run_phase4/7; never pointed at user-supplied files.
    bundle = joblib.load(ROOT / "models" / "hazard.joblib")
    STATE["model"] = bundle["model"]
    STATE["columns"] = bundle["columns"]
    STATE["calibrators"] = joblib.load(ROOT / "models" / "calibrators.joblib")
    STATE["explainer"] = build_explainer(bundle["model"])
    STATE["bands"] = joblib.load(ROOT / "models" / "confidence_bands.joblib")

    thin = joblib.load(ROOT / "models" / "thin_file_tabpfn.joblib")
    STATE["thin_file"] = thin

    STATE["features"] = pd.read_parquet(
        ROOT / "data" / "processed" / "serving_features_enriched.parquet"
    ).set_index("SK_ID_CURR", drop=False)
    scored = pd.read_parquet(ROOT / "data" / "processed" / "phase4_scored_test.parquet")
    STATE["scored_test"] = scored
    STATE["scored_join"] = scored.merge(
        STATE["features"][["SK_ID_CURR", "sector_segment", "data_richness"]].reset_index(
            drop=True
        ),
        on="SK_ID_CURR",
        how="left",
    )
    # SHAP background pool for the thin-file permutation explainer.
    ntc = STATE["features"][STATE["features"]["data_richness"] == "ntc_ntb"]
    STATE["thin_bg"] = ntc[thin["columns"]].sample(
        min(THIN_FILE_BACKGROUND_ROWS, len(ntc)), random_state=42
    )

    STATE["metrics"] = {
        name: json.loads((ROOT / "models" / f"{name}.json").read_text())
        for name in [
            "phase2_metrics",
            "phase3_metrics_target",
            "phase3_metrics_delinquency",
            "phase4_metrics",
            "phase5_metrics",
            "phase6_metrics",
        ]
        if (ROOT / "models" / f"{name}.json").exists()
    }
    STATE["explanations"] = {}
    STATE["fairness_cache"] = None

    # Governance store: tables + append-only triggers.
    store.init_db()

    # Feature store: materialize the scoreable book into the ONLINE store once
    # (empty-store check keeps restarts instant); unseen loans write-through.
    if feature_store.online_count() == 0:
        feature_store.materialize(loan_ids=[int(i) for i in scored["SK_ID_CURR"]])

    # Streaming: event bus + feature-refresh consumer thread (plan.md §14).
    bus = get_bus()
    bus.subscribe(EVENTS_TOPIC, make_feature_refresh_handler(_pd_and_grade))
    bus.start()
    STATE["bus"] = bus


@app.on_event("shutdown")
def stop_bus():
    bus = STATE.get("bus")
    if bus is not None:
        bus.stop()


# ---------------------------------------------------------------- helpers

def _feature_row(loan_id: int) -> tuple[dict, pd.DataFrame]:
    """Serving-path feature access: ONLINE store (write-through on first miss)."""
    try:
        feats = feature_store.get_online_features(loan_id)
    except KeyError:
        raise HTTPException(404, f"Unknown loan_id {loan_id}")
    row = pd.DataFrame([feats])
    for col in row.columns:
        if col not in STRING_COLS:
            row[col] = pd.to_numeric(row[col], errors="coerce")
    return feats, row


def _calibrate(segment: str, raw_pd: float) -> float:
    iso = STATE["calibrators"].get(segment, STATE["calibrators"][GLOBAL_KEY])
    return float(iso.predict([raw_pd])[0])


def _hazard_raw(row: pd.DataFrame) -> tuple[np.ndarray, float]:
    months = pd.concat([row] * MAX_MONTHS, ignore_index=True)
    months["months_since_origination"] = np.arange(1, MAX_MONTHS + 1)
    X = align_columns(build_model_matrix(months), STATE["columns"])
    curve = STATE["model"].predict_proba(X)[:, 1]
    return curve, cumulative_pd(curve)


def _thin_file_raw(row: pd.DataFrame) -> float:
    """TabPFN single-point PD (plan.md §9.3) — clearly a point estimate, no curve."""
    X = row[STATE["thin_file"]["columns"]]
    return float(STATE["thin_file"]["model"].predict_proba(X)[:, 1][0])


def _pd_and_grade(loan_id: int) -> dict:
    """Lightweight full-pipeline re-score (router -> raw -> calibrate -> grade).

    Used by the streaming feature-refresh consumer; no SHAP/narrative work."""
    feats, row = _feature_row(loan_id)
    model_used = route_segment(feats)
    if model_used == "tabpfn_thin_file":
        raw = _thin_file_raw(row)
    else:
        _, raw = _hazard_raw(row)
    calibrated = _calibrate(feats["loan_type_segment"], raw)
    return {
        "calibrated_pd_12m": calibrated,
        "risk_grade": pd_to_grade(calibrated),
        "model_used": model_used,
    }


def _grade_distribution(grades: pd.Series | list) -> dict:
    counts = pd.Series(grades).value_counts()
    return {g: int(counts.get(g, 0)) for g in GRADES}


def _batch_score(feats: pd.DataFrame) -> tuple[np.ndarray, list[str]]:
    """Vectorized hazard + calibration re-scoring of a loan slice (§12.7).

    12-month person-period expansion of every row in one LightGBM call —
    pure re-inference, no retraining."""
    n = len(feats)
    rep = feats.loc[feats.index.repeat(MAX_MONTHS)].reset_index(drop=True)
    rep["months_since_origination"] = np.tile(np.arange(1, MAX_MONTHS + 1), n)
    X = align_columns(build_model_matrix(rep), STATE["columns"])
    hazards = STATE["model"].predict_proba(X)[:, 1].reshape(n, MAX_MONTHS)
    raw = 1.0 - np.prod(1.0 - hazards, axis=1)
    segments = feats["loan_type_segment"].reset_index(drop=True)
    calibrated = apply_calibration(STATE["calibrators"], segments, pd.Series(raw))
    return calibrated, [pd_to_grade(p) for p in calibrated]


# ---------------------------------------------------------------- request models

class DecisionIn(BaseModel):
    decision: str  # 'accept' | 'modify' | 'override'
    reason: str | None = None
    delta: dict | str | None = None  # what a 'modify' changed


class StressIn(BaseModel):
    """§12.7 scenario: magnitude is a signed FRACTION (|m| > 1 is read as a
    percentage). revenue/sector_demand: fractional revenue change (-0.15 =
    15% drop -> obligation ratios scale by 1/(1+m)). rate: fractional increase
    in the annuity/EMI burden (e.g. 0.10 ~ +200bps on a mid-tenor loan)."""

    shock_type: str  # 'revenue' | 'rate' | 'sector_demand'
    magnitude: float
    sector: str | None = None


class EventIn(BaseModel):
    loan_id: int
    type: str  # 'gst_filing' | 'bank_transaction' | 'repayment'
    feature_updates: dict[str, float] | None = None


# ---------------------------------------------------------------- pre-Phase-8 endpoints

@api.get("/loans")
def sample_loans(per_grade: int = 4):
    """A demo-friendly sample: a few loans from every risk grade."""
    scored = STATE["scored_test"]
    sample = (
        scored.sort_values("calibrated_pd_12m")
        .groupby("risk_grade", observed=True)
        .head(per_grade)
    )
    return [
        {
            "loan_id": int(r.SK_ID_CURR),
            "segment": r.loan_type_segment,
            "risk_grade": r.risk_grade,
            "calibrated_pd_12m": round(float(r.calibrated_pd_12m), 4),
        }
        for r in sample.itertuples()
    ]


@api.post("/score/{loan_id}")
def score(loan_id: int):
    """Full §11.3 six-part output: (1) calibrated PD, (2) hazard curve — null on
    the TabPFN thin-file path, which is a labeled point estimate, (3) unified
    risk grade, (4) top-5 SHAP drivers, (5) counterfactual, (6) recommended
    action — plus guarded narrative, confidence band and disclosure.

    Features come from the ONLINE feature store (feature_store.get_online_features);
    every call appends an immutable audit_log row."""
    feats, row = _feature_row(loan_id)
    segment = feats["loan_type_segment"]
    model_used = route_segment(feats)

    if model_used == "tabpfn_thin_file":
        hazard_curve = None
        raw_pd = _thin_file_raw(row)
        drivers = tabpfn_top_drivers(
            STATE["thin_file"]["model"], STATE["thin_bg"], row[STATE["thin_file"]["columns"]]
        )
    else:
        curve, raw_pd = _hazard_raw(row)
        hazard_curve = [round(float(h), 5) for h in curve]
        loan_matrix = row.copy()
        loan_matrix["months_since_origination"] = MAX_MONTHS
        X_row = align_columns(build_model_matrix(loan_matrix), STATE["columns"])
        drivers = top_drivers(STATE["explainer"], X_row)

    # Same per-segment isotonic for both engines: the §9.4/§12.8 unified-scale
    # contract (calibrators were fitted on hazard scores; the thin-file PD is
    # mapped through the same ladder so grades stay comparable).
    calibrated = _calibrate(segment, raw_pd)
    grade = pd_to_grade(calibrated)

    narrative = generate_narrative(drivers, grade, calibrated)

    if model_used == "tabpfn_thin_file":
        counterfactual = {
            "feature": None,
            "reason": (
                "counterfactual grid re-scoring is defined for the hazard engine; "
                "the TabPFN thin-file path returns a labeled point estimate only"
            ),
        }
    else:
        counterfactual = find_counterfactual(
            STATE["model"], STATE["columns"], STATE["calibrators"], segment, row, drivers
        )

    band = confidence_band(STATE["bands"], segment, calibrated)

    result = {
        "loan_id": loan_id,
        "segment": segment,
        "sector": feats.get("sector_segment"),
        "data_richness": feats.get("data_richness"),
        "model_used": model_used,
        "point_estimate": model_used == "tabpfn_thin_file",
        "hazard_curve": hazard_curve,
        "raw_cum_pd_12m": round(float(raw_pd), 4),
        "calibrated_pd_12m": round(calibrated, 4),
        "risk_grade": grade,
        "recommended_action": ACTION_BY_GRADE[grade],
        "top_drivers": drivers,
        "narrative": narrative,
        "counterfactual": counterfactual,
        "confidence_band": band,
        "disclosure": DISCLOSURE,
    }

    store.record_audit(
        loan_id,
        endpoint=f"/api/score/{loan_id}",
        model_used=model_used,
        calibrated_pd=calibrated,
        risk_grade=grade,
        narrative_source=narrative["source"],
        payload=result,
    )
    # Cache the explanation so GET /api/explain never re-scores (§17).
    STATE["explanations"][loan_id] = {
        "loan_id": loan_id,
        "risk_grade": grade,
        "calibrated_pd_12m": round(calibrated, 4),
        "shap_values": drivers,
        "narrative": narrative,
        "counterfactual": counterfactual,
        "confidence_band": band,
    }
    return result


@api.get("/metrics")
def metrics():
    return STATE["metrics"]


@api.post("/override/{loan_id}")
def override(loan_id: int, body: DecisionIn):
    """§12.5 decision log: accept | modify | override. Reason is MANDATORY for
    both modify and override; a modify records its delta. Append-only."""
    if body.decision not in store.DECISIONS:
        raise HTTPException(422, f"decision must be one of {list(store.DECISIONS)}")
    if body.decision in ("modify", "override") and not (body.reason and body.reason.strip()):
        raise HTTPException(
            422, f"A reason is mandatory when you {body.decision} the AI assessment."
        )

    scored = STATE["scored_test"]
    row = scored[scored["SK_ID_CURR"] == loan_id]
    grade = row.iloc[0]["risk_grade"] if len(row) else None
    pd_val = float(row.iloc[0]["calibrated_pd_12m"]) if len(row) else None

    record_id = store.record_decision(
        loan_id, body.decision, body.reason, grade, pd_val, delta=body.delta
    )
    return {"logged": True, "record_id": record_id}


@api.get("/overrides")
def overrides(limit: int = 50):
    return store.list_decisions(limit)


# ---------------------------------------------------------------- Phase 8 additions

@api.get("/explain/{loan_id}")
def explain(loan_id: int):
    """Cached three-level explanation, no re-scoring (§17)."""
    cached = STATE["explanations"].get(loan_id)
    if cached is None:
        raise HTTPException(
            404,
            {
                "error": f"loan {loan_id} has not been scored in this serving session",
                "hint": f"POST /api/score/{loan_id} first, then re-request the explanation",
            },
        )
    return cached


@api.get("/portfolio/summary")
def portfolio_summary():
    """Grade distribution + expected-loss rate + segment counts (§17)."""
    scored = STATE["scored_join"]
    dist = _grade_distribution(scored["risk_grade"])
    total = len(scored)
    return {
        "n_loans": int(total),
        "grade_distribution": dist,
        "grade_shares": {g: round(c / total, 4) for g, c in dist.items()},
        "expected_loss_rate": round(float((scored["calibrated_pd_12m"] * LGD).mean()), 5),
        "el_convention": EL_CONVENTION,
        "counts_by_segment": {
            "loan_type_segment": {
                str(k): int(v)
                for k, v in scored["loan_type_segment"].value_counts().items()
            },
            "sector_segment": {
                str(k): int(v) for k, v in scored["sector_segment"].value_counts().items()
            },
            "data_richness": {
                str(k): int(v) for k, v in scored["data_richness"].value_counts().items()
            },
        },
    }


@api.post("/stress-test")
def stress_test(body: StressIn):
    """§12.7 scenario simulator: perturb mapped features on the OOT scored
    slice, re-score through hazard + calibration (pure re-inference), report
    pre/post grade distributions and the delta expected-loss rate.

    Sampling: up to STRESS_MAX_LOANS loans (random_state=42) — the 12-month
    person-period expansion keeps the whole run sub-second; the sample size
    and flag are stated in the response."""
    if body.shock_type not in STRESS_SHOCKS:
        raise HTTPException(422, f"shock_type must be one of {list(STRESS_SHOCKS)}")
    magnitude = body.magnitude
    if abs(magnitude) > 1.0:  # forgiving: -15 means -15%
        magnitude = magnitude / 100.0
    if body.shock_type in ("revenue", "sector_demand") and magnitude <= -1.0:
        raise HTTPException(422, "revenue shock magnitude must be > -1 (a fraction)")

    scored = STATE["scored_join"]
    sampled = len(scored) > STRESS_MAX_LOANS
    sample = scored.sample(STRESS_MAX_LOANS, random_state=42) if sampled else scored
    feats = STATE["features"].loc[sample["SK_ID_CURR"]]

    if body.shock_type == "sector_demand":
        if not body.sector:
            raise HTTPException(422, "sector is required for a sector_demand shock")
        mask = feats["sector_segment"] == body.sector
        if not mask.any():
            known = sorted(STATE["features"]["sector_segment"].dropna().unique())
            raise HTTPException(422, f"unknown sector '{body.sector}'; known: {known}")
    else:
        mask = pd.Series(True, index=feats.index)

    shocked = feats.copy()
    if body.shock_type in ("revenue", "sector_demand"):
        # Revenue/income moves by (1+m); obligation ratios scale by 1/(1+m).
        ratio_factor = 1.0 / (1.0 + magnitude)
        for col in ("credit_income_ratio", "annuity_income_ratio"):
            shocked.loc[mask, col] = shocked.loc[mask, col] * ratio_factor
    else:  # rate shock: EMI burden rises by the given fraction
        shocked.loc[mask, "annuity_income_ratio"] = shocked.loc[
            mask, "annuity_income_ratio"
        ] * (1.0 + magnitude)

    pre_pd, pre_grades = _batch_score(feats)
    post_pd, post_grades = _batch_score(shocked)

    pre_el = float(np.mean(pre_pd) * LGD)
    post_el = float(np.mean(post_pd) * LGD)
    return {
        "shock_type": body.shock_type,
        "magnitude": magnitude,
        "sector": body.sector,
        "n_loans_scored": int(len(feats)),
        "n_loans_shocked": int(mask.sum()),
        "sampled": sampled,
        "sampling_note": (
            f"random sample of {STRESS_MAX_LOANS} of {len(scored)} OOT loans "
            f"(random_state=42); 12-month person-period re-inference"
            if sampled
            else "full OOT scored slice re-scored"
        ),
        "pre_shock_distribution": _grade_distribution(pre_grades),
        "post_shock_distribution": _grade_distribution(post_grades),
        "pre_expected_loss_rate": round(pre_el, 5),
        "post_expected_loss_rate": round(post_el, 5),
        "delta_expected_loss_rate": round(post_el - pre_el, 5),
        "el_convention": EL_CONVENTION,
    }


@api.get("/fairness/audit")
def fairness():
    """§12.6 disparate-impact summary (computed once per process, then cached)."""
    if STATE.get("fairness_cache") is None:
        STATE["fairness_cache"] = fairness_audit()
    return STATE["fairness_cache"]


@api.get("/rbi/mapping")
def rbi_mapping():
    """§12.4 read-only ML-trigger -> RBI indicator mapping + state machine."""
    return get_rbi_mapping()


@api.get("/drift/report")
def drift_report():
    """Latest Phase 10 drift summary; honest placeholder until it exists."""
    path = ROOT / "reports" / "drift_summary.json"
    if not path.exists():
        return {
            "status": "not_yet_generated",
            "hint": (
                "Run the Phase 10 MLOps drift job to write reports/drift_summary.json "
                "(Evidently AI data/prediction-drift summary)."
            ),
        }
    return json.loads(path.read_text())


@api.get("/alerts")
def alerts(limit: int = 50):
    """Streaming re-score alerts — rows exist only where a risk grade MOVED (§14)."""
    return store.list_alerts(limit)


@api.get("/timeline/{loan_id}")
def timeline(loan_id: int, limit: int = 100):
    """Silent risk-trajectory timeline for one loan (§14)."""
    return store.list_timeline(loan_id, limit)


@api.post("/events/simulate")
def simulate_event(body: EventIn):
    """Publish a simulated GST-filing / bank-transaction / repayment event onto
    the bus (§14). If feature_updates is omitted, a documented default is
    derived from the loan's CURRENT online features:

      gst_filing       (distress) — GST-turnover-drop proxy: a ~30% reported-income
                        drop inflates credit_income_ratio and annuity_income_ratio
                        by 1.4x, and sustained turnover stress surfaces as payment
                        strain on existing obligations (bureau_overdue_flag -> 1,
                        prior_late_rate +0.2). No direct GST features exist in the
                        Home Credit proxy snapshot, so the drop is mapped onto the
                        model-consumed stress features; real GSTN fields plug in
                        here once sandbox data arrives (plan.md §6.1, §12.4).
      bank_transaction (distress) — bureau_overdue_flag -> 1, prior_late_rate +0.2
                        (clipped at 1.0).
      repayment        (positive) — prior_late_rate improves by 20%.

    The consumer thread refreshes the online store, re-scores the loan through
    the full pipeline, and inserts an alert row if the grade moved (otherwise
    a silent risk_timeline row) — poll GET /api/alerts / /api/timeline."""
    if body.type not in EVENT_TYPES:
        raise HTTPException(422, f"type must be one of {list(EVENT_TYPES)}")
    try:
        feats = feature_store.get_online_features(body.loan_id)
    except KeyError:
        raise HTTPException(404, f"Unknown loan_id {body.loan_id}")

    updates = body.feature_updates
    if not updates:
        if body.type == "gst_filing":
            updates = {
                col: round(float(feats[col]) * 1.4, 6)
                for col in ("credit_income_ratio", "annuity_income_ratio")
                if feats.get(col) is not None
            }
            # GST turnover stress shows up as payment strain in this proxy
            # feature space (see docstring) — without these the shock can land
            # entirely on features the tree model never splits on.
            updates["bureau_overdue_flag"] = 1.0
            updates["prior_late_rate"] = round(
                min(1.0, float(feats.get("prior_late_rate") or 0.0) + 0.2), 6
            )
        elif body.type == "bank_transaction":
            base = feats.get("prior_late_rate") or 0.0
            updates = {
                "bureau_overdue_flag": 1.0,
                "prior_late_rate": round(min(1.0, float(base) + 0.2), 6),
            }
        else:  # repayment
            base = feats.get("prior_late_rate") or 0.0
            updates = {"prior_late_rate": round(max(0.0, float(base) * 0.8), 6)}

    event = {"loan_id": body.loan_id, "type": body.type, "feature_updates": updates}
    event_id = STATE["bus"].publish(EVENTS_TOPIC, event)
    return {
        "published": True,
        "event_id": event_id,
        "topic": EVENTS_TOPIC,
        "loan_id": body.loan_id,
        "event_type": body.type,
        "feature_updates": updates,
        "hint": "poll GET /api/alerts (grade moved) or GET /api/timeline/{loan_id} (silent)",
    }


app.include_router(api)

# Production: serve the built React app from this same process (routes above
# take precedence; everything else falls through to the SPA).
_DIST = ROOT / "frontend" / "dist"
if _DIST.exists():
    app.mount("/", StaticFiles(directory=_DIST, html=True), name="frontend")
